-- hs_programs seed — 1 row
-- Source: hs_programs.csv (local, 2026-03-25)
-- Project: gritty-recruit-hub-rebuild | Supabase ref: xyudnajzhuwdauwkwsbh
-- Generated by: David (Data Steward)

INSERT INTO public.hs_programs (
  school_name,
  city,
  state,
  zip,
  address,
  conference,
  division,
  state_athletic_association
)
VALUES (
  'Boston College High School',
  'Boston',
  'MA',
  '02125',
  '150 Morrissey Blvd.',
  'Catholic Conference',
  'D1',
  'MIAA'
)
ON CONFLICT (school_name, state) DO NOTHING;
